### PR TITLE
Add Code Scanning alerts bulk dismissal workflow AB#196 AB#203 AB#209 AB#210

### PR DESCRIPTION
**Pull request by AleksIvanovSinglet**
- it works by manual activation only (thus needs to exist in default branch for the option to appear)
- requires several secrets to work

### CODE REVIEW

**Comment by AleksIvanovSinglet** [comment]
NOTE: main.yml fails, because the required condition for the "Send SonarCloud results", **still hasn't been added**

**Review by kulov — APPROVED** [review]
great work!

**Comment by kulov** [comment]
Can we dismiss only issues related to code generated files?

**Comment by AleksIvanovSinglet** [comment]
> Can we dismiss only issues related to code generated files?

Good idea, would research.

**Pull request merged**
