### PR TITLE
Add AppCenterSecret assignment in build process from GitHub Secrets AB#325

### PR DESCRIPTION
**Pull request by aleks-ivanov**
- add "Assign_AppCenterSecret_From_MSBuild" as placeholder for AppCenterSecret variable in App.xaml.cs
- add /p:AppCenterSecret=$env:APP_CENTER_SECRET parameter with ${{ secrets.APP_CENTER_SECRET }} as value
- add Target "AssignAppCenterSecret" in Notepads.csproj, that executes before any other declared targets, which takes the value of the /p:AppCenterSecret parameter and replaces the "Assign_AppCenterSecret_From_MSBuild" placeholder in App.xaml.cs
- during the run **in the original repo ONLY**, the value of ${{ secrets.APP_CENTER_SECRET }} is exposed to anyone with permissions to change and commit files, by adding a step to the main workflow to upload the App.xaml.cs file as artifact

### CODE REVIEW

**Review by kulov — COMMENTED** [review]
@aleks-ivanov Does this build step work properly when build is run locally using Visual Studio?

**Comment by aleks-ivanov** [comment]
> @aleks-ivanov Does this build step work properly when build is run locally using Visual Studio?

@kulov it does, but I think I know why you are asking the question and may be we can do the replacement like this:

.Replace('AppCenterSecret = null','AppCenterSecret = "$(AppCenterSecret)"')

**Review by kulov — APPROVED** [review]

**Review by kulov — CHANGES_REQUESTED** [review]
Please review failing checks.

**Comment by aleks-ivanov** [comment]
> Please review failing checks.

@kulov the fix was on the way, just had to verify with local build 🙂

**Pull request merged**
